### ISSUE TITLE
README.md links not working

### ISSUE THREAD

**Issue by ptlambert** [GoalZero26503/yeti-wifi-public#1]
Links on README.md currently point to github.io instead of .github.com and they are returning 404 (for me at least).

**Comment by BillXMA** [comment]
+1

**Comment by astout** [comment]
Thanks for pointing it out. [README](https://github.com/GoalZero26503/yeti-wifi-public/blob/master/README.md) redirects to the [wiki](https://github.com/GoalZero26503/yeti-wifi-public/wiki)

Closing: https://github.com/GoalZero26503/yeti-wifi-public/commit/fb36cbb836721dae2e473a3c8ef27a630c7661b0
