### ISSUE TITLE
Release notes for 1.5.7 firmware missing

### ISSUE THREAD

**Issue by BillXMA** [GoalZero26503/yeti-wifi-public#2]
Looks like the release notes have not been updated for the 1.5.7 public release

**Comment by astout** [comment]
Content was unintentionally left in the repo, the Help Guide is in the wiki. Please see here: https://github.com/GoalZero26503/yeti-wifi-public/wiki/Yeti-1500X-3000X-6000X-Firmware-Release-Notes
